# fly.toml app configuration file generated for dayta-backend on 2025-11-26T14:09:19Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'dayta-backend'
primary_region = 'cdg'

[build]

[processes]
  app = 'uvicorn main:app --host 0.0.0.0 --port 8080'

[http_service]
  internal_port = 8077
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
